# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'helper_form.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(984, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.dspBxStart = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.dspBxStart.setMaximum(9999.99)
        self.dspBxStart.setSingleStep(0.1)
        self.dspBxStart.setProperty("value", 0.1)
        self.dspBxStart.setObjectName("dspBxStart")
        self.gridLayout.addWidget(self.dspBxStart, 2, 3, 1, 1)
        self.btnAdd = QtWidgets.QPushButton(self.centralwidget)
        self.btnAdd.setObjectName("btnAdd")
        self.gridLayout.addWidget(self.btnAdd, 2, 6, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.tableWidget, 3, 0, 1, 10)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.btnActivate = QtWidgets.QPushButton(self.centralwidget)
        self.btnActivate.setObjectName("btnActivate")
        self.gridLayout.addWidget(self.btnActivate, 2, 7, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 2, 1, 1)
        self.spBxCount = QtWidgets.QSpinBox(self.centralwidget)
        self.spBxCount.setMaximum(999999)
        self.spBxCount.setProperty("value", 50)
        self.spBxCount.setObjectName("spBxCount")
        self.gridLayout.addWidget(self.spBxCount, 2, 1, 1, 1)
        self.btnDelete = QtWidgets.QPushButton(self.centralwidget)
        self.btnDelete.setObjectName("btnDelete")
        self.gridLayout.addWidget(self.btnDelete, 2, 9, 1, 1)
        self.btnDeactivate = QtWidgets.QPushButton(self.centralwidget)
        self.btnDeactivate.setObjectName("btnDeactivate")
        self.gridLayout.addWidget(self.btnDeactivate, 2, 8, 1, 1)
        self.btnConnect = QtWidgets.QPushButton(self.centralwidget)
        self.btnConnect.setObjectName("btnConnect")
        self.gridLayout.addWidget(self.btnConnect, 1, 0, 1, 10)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 4, 1, 1)
        self.dspBxEnd = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.dspBxEnd.setMaximum(9999.99)
        self.dspBxEnd.setSingleStep(0.1)
        self.dspBxEnd.setProperty("value", 1.0)
        self.dspBxEnd.setObjectName("dspBxEnd")
        self.gridLayout.addWidget(self.dspBxEnd, 2, 5, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 1)
        self.leInstrument = QtWidgets.QLineEdit(self.groupBox)
        self.leInstrument.setObjectName("leInstrument")
        self.gridLayout_2.addWidget(self.leInstrument, 3, 0, 1, 4)
        self.sBxID = QtWidgets.QSpinBox(self.groupBox)
        self.sBxID.setEnabled(False)
        self.sBxID.setObjectName("sBxID")
        self.gridLayout_2.addWidget(self.sBxID, 1, 0, 1, 1)
        self.chBxLogic = QtWidgets.QCheckBox(self.groupBox)
        self.chBxLogic.setObjectName("chBxLogic")
        self.gridLayout_2.addWidget(self.chBxLogic, 6, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 4, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 7, 1, 1, 1)
        self.dsBxBuy = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.dsBxBuy.setSingleStep(0.1)
        self.dsBxBuy.setObjectName("dsBxBuy")
        self.gridLayout_2.addWidget(self.dsBxBuy, 5, 0, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 4, 0, 1, 1)
        self.sBxDelay = QtWidgets.QSpinBox(self.groupBox)
        self.sBxDelay.setObjectName("sBxDelay")
        self.gridLayout_2.addWidget(self.sBxDelay, 8, 0, 1, 1)
        self.leIP = QtWidgets.QLineEdit(self.groupBox)
        self.leIP.setObjectName("leIP")
        self.gridLayout_2.addWidget(self.leIP, 8, 1, 1, 3)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 7, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 11, 0, 1, 1)
        self.dsBxSell = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.dsBxSell.setMinimum(-99.0)
        self.dsBxSell.setSingleStep(0.1)
        self.dsBxSell.setObjectName("dsBxSell")
        self.gridLayout_2.addWidget(self.dsBxSell, 5, 2, 1, 2)
        self.chBxActive = QtWidgets.QCheckBox(self.groupBox)
        self.chBxActive.setObjectName("chBxActive")
        self.gridLayout_2.addWidget(self.chBxActive, 6, 1, 1, 1)
        self.chBxStop = QtWidgets.QCheckBox(self.groupBox)
        self.chBxStop.setObjectName("chBxStop")
        self.gridLayout_2.addWidget(self.chBxStop, 6, 2, 1, 1)
        self.btnChange = QtWidgets.QPushButton(self.groupBox)
        self.btnChange.setObjectName("btnChange")
        self.gridLayout_2.addWidget(self.btnChange, 9, 0, 1, 4)
        self.gridLayout.addWidget(self.groupBox, 1, 10, 3, 1)
        self.gridLayout.setColumnStretch(0, 2)
        self.gridLayout.setColumnStretch(1, 2)
        self.gridLayout.setColumnStretch(2, 2)
        self.gridLayout.setColumnStretch(3, 2)
        self.gridLayout.setColumnStretch(4, 2)
        self.gridLayout.setColumnStretch(5, 2)
        self.gridLayout.setColumnStretch(6, 2)
        self.gridLayout.setColumnStretch(7, 2)
        self.gridLayout.setColumnStretch(8, 2)
        self.gridLayout.setColumnStretch(9, 2)
        self.gridLayout.setColumnStretch(10, 6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 984, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Database helper 3000"))
        self.btnAdd.setText(_translate("MainWindow", "Add"))
        self.label.setText(_translate("MainWindow", "Count"))
        self.btnActivate.setText(_translate("MainWindow", "Activate"))
        self.label_2.setText(_translate("MainWindow", "Start"))
        self.btnDelete.setText(_translate("MainWindow", "Delete"))
        self.btnDeactivate.setText(_translate("MainWindow", "Deactivate"))
        self.btnConnect.setText(_translate("MainWindow", "Connect"))
        self.label_3.setText(_translate("MainWindow", "End"))
        self.groupBox.setTitle(_translate("MainWindow", "Client"))
        self.label_4.setText(_translate("MainWindow", "ID"))
        self.label_5.setText(_translate("MainWindow", "Instrument"))
        self.chBxLogic.setText(_translate("MainWindow", "Logic"))
        self.label_8.setText(_translate("MainWindow", "Sell"))
        self.label_12.setText(_translate("MainWindow", "IP"))
        self.label_6.setText(_translate("MainWindow", "Buy"))
        self.label_10.setText(_translate("MainWindow", "Delay"))
        self.chBxActive.setText(_translate("MainWindow", "Active"))
        self.chBxStop.setText(_translate("MainWindow", "Stop"))
        self.btnChange.setText(_translate("MainWindow", "Change"))
